// This file is automatically generated by CMake using the version.h.in template,
// based on data obtained from the GenerateVersion.cmake script.

#ifndef VI_TIMING_SOURCE_VERSION_H
#	define VI_TIMING_SOURCE_VERSION_H
#	pragma once

#include <cstdint>
#include <string_view>

namespace misc
{
	constexpr unsigned VI_TM_VERSION_MAJOR = 0+0U;
	constexpr unsigned VI_TM_VERSION_MINOR = 1+0U;
	constexpr unsigned VI_TM_VERSION_PATCH = +0U;

	constexpr std::string_view VI_TM_GIT_DESCRIBE = "v0.1-4-g130e860";
	constexpr std::string_view VI_TM_GIT_COMMIT = "130e860f7d8da87993c8098e536917766469d144";
	constexpr std::string_view VI_TM_GIT_DATETIME = "2025-07-27 22:40:31 +0300";

	// Build Number Generator: Formats the build number using the compilation date and time. Example: 2506170933U.
	// Updates the global variable based on the last compilation time.
	std::uint32_t build_number_updater(const char(&date)[12], const char(&time)[9]);
	// Next line will be called in each translation unit.
	static const std::uint32_t dummy_build_number_updater = build_number_updater(__DATE__, __TIME__);

	// Returns a number based on the date and time of the last compilation.
	std::uint32_t build_number_get();
}

#endif // #ifndef VI_TIMING_SOURCE_VERSION_H
